### ISSUE TITLE
App won't run with latest version of Electron due to nodeIntegration defaulting to off.

### ISSUE THREAD

**Issue by RocketManRC** [w0js/js8UdpTcpBridge#9]
Here is the fix. In main.js change:
```
  mainWindow = new BrowserWindow({width: 800, height: 600})
```
To:
```
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
```

**Comment by w0js** [comment]
I have neglected this repo after updates to JS8CALL added functionality for this very issue. I realize it is useful for other things as well, so I will get to it shortly. Thanks for the report. Sorry the response is so late.
